---
version: 0.2

phases:
  install:
    commands:
      - yum install -y zip
      - amazon-linux-extras install docker -y
      - dockerd &> dockerd-logfile &
  build:
    commands:
      - npm install
      - npm run build
      - scripts/codebuild-artifacts.sh
