export const headers =[
    "Hearing Date",
    "Court",
    "Force",
    "Urgent",
    "Defendant",
    "DoB",
    "ASN",
    "URN",
    "Triggers",
    "Errors",
    "Offence Code",
    "Offence Start Date (Incident date)",
    "Offence Location",
    "1st Result Code",
    "1st Result Duration / Amount",
    "1st Result Text",
    "1st Result Qualifiers",
    "2nd Result Code",
    "2nd Result Duration / Amount",
    "2nd Result Text",
    "2nd Result Qualifiers",
    "3rd Result Code",
    "3rd Result Duration / Amount",
    "3rd Result Text",
    "3rd Result Qualifiers",
    "4th Result Code",
    "4th Result Duration / Amount",
    "4th Result Text",
    "4th Result Qualifiers",
    "5th Result Code",
    "5th Result Duration / Amount",
    "5th Result Text",
    "5th Result Qualifiers",
    "6th Result Code",
    "6th Result Duration / Amount",
    "6th Result Text",
    "6th Result Qualifiers",
    "7th Result Code",
    "7th Result Duration / Amount",
    "7th Result Text",
    "7th Result Qualifiers",
    "8th Result Code",
    "8th Result Duration / Amount",
    "8th Result Text",
    "8th Result Qualifiers",
    "9th Result Code",
    "9th Result Duration / Amount",
    "9th Result Text",
    "9th Result Qualifiers",
    "10th Result Code",
    "10th Result Duration / Amount",
    "10th Result Text",
    "10th Result Qualifiers",
    "Trigger Locked By",
    "Exception Locked By"
]
