version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          command: make build
          name: Build project
      - persist_to_workspace:
          root: .
          paths: .
      - notify_slack_failure
