version: 2.1

commands:
  restore_all_caches:
    description: Restore all of the node modules directories
    steps:
      - run:
          name: Hash package locks
          command: bash ./scripts/hash-package-locks.sh
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}

  save_all_caches:
    description: Save all of the node_modules directories
    steps:
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}
          paths: node_modules

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:2022.10.1
      docker_layer_caching: true
    resource_class: large
    working_directory: ~
    steps:
      - checkout
      - restore_all_caches
      - run: npm install
      - save_all_caches
      - run: npm run build
      - run: npm run lint
      - add_ssh_keys:
          fingerprints:
            - 2e:0e:60:da:7c:5e:82:5e:cd:01:b8:e1:02:30:25:da
      - run:
          name: Clone Core
          command: git clone --depth 1 git@github.com:ministryofjustice/bichard7-next-core.git ~/bichard7-next-core
      - run:
          name: Run Postgres
          command: cd ~/bichard7-next-core && npm run postgres
      - run: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
