version: 2.1

commands:
  restore_all_caches:
    description: Restore all of the node modules directories
    steps:
      - run:
          name: Hash package locks
          command: bash ./scripts/hash-package-locks.sh
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}

  save_all_caches:
    description: Save all of the node_modules directories
    steps:
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}
          paths: node_modules

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:2022.10.1
      docker_layer_caching: true
    resource_class: large
    working_directory: ~
    steps:
      - checkout
      - restore_all_caches
      - run: npm install
      - save_all_caches
      - run: npm run build
      - run: npm run lint
      - add_ssh_keys:
          fingerprints:
            - c6:d2:90:a6:86:0d:a0:d7:c2:0b:6e:b2:81:c8:f4:17
      - run:
          command: ssh-add -D
      - run:
          command: ssh-add ~/.ssh/id_rsa_c6d290a6860da0d7c20b6eb281c8f417
      - run:
          name: Clone Bichard7 Next
          command: git clone --depth 1 git@github.com:ministryofjustice/bichard7-next.git ~/bichard7-next
      - run:
          name: Run Postgres
          command: cd ~/bichard7-next && make run-pg
      - run: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
