name: Build and Test

on:
  workflow_dispatch:
  push:

env:
  TZ: Europe/London

jobs:
  build_and_test:
    name: Build and Test Reporting
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./work

    steps:
      - name: Checkout repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          path: '~/bichard7-next-reporting'

      - name: Setup node version
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc
          
      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@805c9da24fe7083e24b8435a626463b25951d278 # v1.4.0
      
      - name: Print working directory
        run: |
          pwd
          ls 

      - name: Install dependencies
        run: npm ci --ignore-scripts
      
      - name: Print working directory
        run: |
          pwd
          ls 

      - name: Run build
        run: npm run build
      
      - name: Print working directory
        run: |
          pwd
          ls 

      - name: Checkout Core Repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          repository: 'ministryofjustice/bichard7-next-core'
          token: ${{ secrets.GH_PAT_TOKEN }}
          path: '~/bichard7-next-core'
          fetch-depth: 1

      - name: Print working directory
        run: |
          pwd
          ls 
    
      - name: Install core dependencies
        working-directory: ~/bichard7-next-core
        run: npm ci --ignore-scripts

      - name: Print working directory
        run: |
          pwd
          ls 

      - name: Run Postgres and LocalStack
        working-directory: ~/bichard7-next-core
        run: |
          npm run postgres
          npm run localstack

      - name: Print working directory
        run: |
          pwd
          ls 

      - name: Run test
        working-directory: ~/bichard7-next-reporting
        run: |
          pwd
          ls
          npm run test